name: Run integration tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for Docker Compose)
        uses: docker/setup-qemu-action@v3

      - name: Copy .env.example to .env
        run: cp ./intergeration/.env.example ./intergeration/.env

      - name: Run intergeration script
        run: cd intergeration && npm run test:intergeration
